version = '2'

[linters]
default = 'all'
disable = [
  'depguard',
  'godoclint',
  'gomoddirectives',
  'gosec',
  'ireturn',
  'musttag',
  'nlreturn',
  'noctx',
  'recvcheck',
  'wsl',
]

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = "var-naming"
disabled = true

[linters.settings.varnamelen]
ignore-names = [
  'a',
  'b',
  'c',
  'd',
  'i',
  'j',
  'k',
  'n',
  'm',
  'ok',
  're',
  'im',
  'pi',
  'p',
  'in',
  's',
  'a0',
  'a1',
  'a2',
  'a3',
  'a4',
  'tt',
  'tw',
  't0',
  't1',
  't2',
  't3',
  'w1',
  'w2',
  'w3',
  'w4',
  'w',
  'h',
  'x',
  'y',
  'z',
  'e0',
  'e1',
  'e2',
  'e3',
  'o0',
  'o1',
  'o2',
  'o3',
  'x0',
  'x1',
  'x2',
  'x3',
  'x4',
  'y0',
  'y1',
  'y2',
  'y3',
  'y4',
]
ignore-decls = ['T any', 'T Complex']

[linters.settings.wsl_v5]
allow-first-in-block = true
branch-max-lines = 2
allow-whole-block = false

[linters.exclusions]
generated = 'lax'
presets = ['comments', 'common-false-positives', 'legacy', 'std-error-handling']
paths = ['third_party$', 'builtin$', 'examples$']

[[linters.exclusions.rules]]
linters = ['mnd']
path = '.*\.go'

[[linters.exclusions.rules]]
linters = ['testpackage']
path = '.*_test\.go'

[severity]
default = 'warn'

[[severity.rules]]
linters = ['exhaustive', 'exhaustruct', 'godox']
severity = 'info'

[formatters]
enable = ['gofumpt', 'goimports']

[formatters.exclusions]
generated = 'lax'
paths = ['third_party$', 'builtin$', 'examples$']
